# Generated by Django 5.1.2 on 2024-10-17 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_congreso_university_person_university'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='congreso',
        ),
        migrations.AddField(
            model_name='congreso',
            name='roles',
            field=models.ManyToManyField(related_name='congress_roles', to='general.rol'),
        ),
    ]
