# Generated by Django 5.1.2 on 2024-10-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_remove_rol_congreso_congreso_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='last_name',
        ),
    ]
