# Generated by Django 5.1.2 on 2024-10-17 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_remove_person_first_name_remove_person_last_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rol',
            name='owner',
        ),
        migrations.AddField(
            model_name='person',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
