# Generated by Django 5.1.2 on 2024-10-17 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0010_remove_rol_owner_person_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='congreso',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='person',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='rol',
            name='is_active',
        ),
    ]
