# Generated by Django 5.1.2 on 2024-10-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_remove_congreso_is_active_remove_person_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='congreso',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='entidad',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rol',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='university',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
